### ISSUE TITLE
Chapter order is unclear

### ISSUE THREAD

**Issue by Hoverbear** [skade/rust-three-days-course#1]
Currently there is no clear indication of chapter ordering beyond the following:

* Intro
* Installation

**Comment by skade** [comment]
Yes, also for the reason that it isn't fully clear yet.

But there's definitely a TOC missing go group things.

**Comment by Hoverbear** [comment]
I propose the following ordering:

### Day 1

Goal: Get Rust working, get them writing basic programs and being comfortable looking at the basic syntax. Introduce things like `match` and iterators to get them to go "wow" and want to learn more.

1. **Introduction:** A bit about Rust from a high level.
1. **Installing:** Rustup, setting up.
1. **Data Structures:** Introduce syntax for primitives, structs, enums, tuples.
1. **Functions:** Basic (non-generic) functions. Mutability/ownership alluded to, but not shown/explained.
1. **Traits:** Implementing traits on structs. (Use example struct/functions from previous chapters)
1. **Little Helpers:** Strings without thinking, `Debug`, `println!()`, code style.
1. **Match:** Introduce `match` and show it handling enums and other things.
1. **Iterators:** (Currently missing entirely!) Introduce lazy iterators and show a few basic examples. 
1. **Documentation:** Introduce documentation, how to write docs, how to navigate the API docs.
1. **Testing:** Show testing strategies. Inline, module, integration, documentation.

### Day 2

Goal: Introduce generics, show idioms, and get them thinking about deeper topics. Finish with ownership and let them consider the rules until next day.

1. **Generics:** Ease back into things by expanding on Functions to show generics. Follow with showing generic structs and traits. Serves to re-introduce the topics from the first day.
1. **Standard Types:** Now that they understand generics show them `Option` and `Result` etc. Have a conversation about their implications.
1. **Errors:** Show error handling techniques such as `?` and `map` etc. Talk about raising errors through a program.
1. **Strings:** Show different types of strings, talk about why they exist, and show how to accept `str` or `String`, for example. Leads into a discussion about converting types.
1. **Conversion Patterns:** Introduce `From`, `Into`, etc. Discuss accepted semantics around naming for conversions.
1. **Ownership:** Open up a conversation about ownership, show a few examples of borrowing, talk about the basic ownership rules.

### Day 3

Goal: Introduce advanced ideas like lifetimes, sizedness, etc. Gets them to do some threading. Encourage them to think about nuts and bolts.

1. **Mutability:** Re-introduces ownership principles as mutability and inner mutability is discussed.
1. **Lifetimes:** Just the basics, work with some functions that utilize lifetimes.
1. **Threading:** Get them able to spawn threads so later discussions about `Rc` etc make sense. Circle back and talk about how ownership relates to threading.
1. **Smart Pointers:** Show them to use `Rc` and `Arc` etc to solve new problems in basic multi-threading examples.
1. **Sizedness:** Discuss the idea of the `Sized` type and how to resolve common issues with it.
1. **Memory Considerations:** Some nuts and bolts around how memory layout and allocation works. Show why we don't need a GC.
1. **Nightly:** Talk about why nightly might be something to use, show how to use it.

**Comment by skade** [comment]
The "little helper" part is actually intended _right_ after data structures, and I would move match and stuff further up. A small introduction into generics has to be given early, as well as error handling, as it's everywhere in daily use. I would move the standard types further up.

Ownership should be introduced on the first day _very early_.

I'll post a reordering later :).

**Comment by Hoverbear** [comment]
Sounds good

**Comment by skade** [comment]
Also see the newly added table of contents (unfinished).
