### ISSUE TITLE
Slides seem to be broken

### ISSUE THREAD

**Issue by aochagavia** [skade/rust-three-days-course#119]
# Description of the issue

When I visit my local version of the course, the slides don't work. I get to see this:

![issue](https://user-images.githubusercontent.com/5196584/38605588-10255ba6-3d74-11e8-8cff-97a2fe47ae0e.png)

While I expected this:

![expected](https://user-images.githubusercontent.com/5196584/38605586-0ffb212e-3d74-11e8-8a7f-821c3d4b680f.png)

# Additional details

This happens both on Firefox and Chrome. Also, the slides on https://skade.github.io/rust-three-days-course/presentation/index.html?chapter=overview&locale=en-US#/ work perfectly fine on both browsers.

# Steps to reproduce

First, start an http server on the root directory:

```
python -m http.server
```

Then visit http://127.0.0.1:8000/presentation/index.html?chapter=overview&locale=en-US#/

**Comment by badboy** [comment]
I can't reproduce that locally (macOS, Firefox 61).
Do you have any errors in the web console? (To open: Tools -> Web Developer -> Web Console).
Also check the `Network` tab to see if it fails to load the CSS/JS files.

**Comment by aochagavia** [comment]
Upon further consideration, it looks like this is a Windows issue. Cloning and serving the repository on Ubuntu works flawlessly. Not so on Windows. I haven't the slightest clue of what is going on here.

**Comment by badboy** [comment]
Any errors though? I don't have a Windows machine at hand to check it, but I'd still like this to get fixed if there's a problem.

**Comment by aochagavia** [comment]
Just tried to reproduce it again... but now everything works correctly.

¯\_(ツ)_/¯

I guess we can close this issue?

**Comment by badboy** [comment]
Yep, if it can't be reproduced. Thanks for opening and trying though.
