### ISSUE TITLE
Deref-coersions and Conversion Patterns similar

### ISSUE THREAD

**Issue by Hoverbear** [skade/rust-three-days-course#12]
With Deref coersions already partially discussed in the Strings chapter, and them being a conversion pattern, it seems like it might be reasonable to incorporate the topic into the Conversion Patterns chapter.

Then again, this might make the Conversion Patterns chapter quite large, so keeping them split might be a good idea.

**Comment by skade** [comment]
I think Deref conversions merit their own chapter as they might happen implicitly and are somewhat "magic" and have compiler support, while From, Into, AsRef and friends are more conventions to follow and know.
