### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by emig** [skade/rust-three-days-course#53]
Tried using: https://skade.github.io/rust-three-days-course/presentation/index.html
getting the same results as running locally.

expected: index page that lets me navigate the presentation/index the contents
got: index page that lets select a language but not going through the presentation

**Comment by Hoverbear** [comment]
You're looking for https://github.com/skade/rust-three-days-course/tree/master/courses probably

**Comment by emig** [comment]
Wouldn't it be better to have the course index on the index page itself?

![screen shot 2017-04-21 at 15 22 11](https://cloud.githubusercontent.com/assets/1539793/25279425/b4643e2a-26a6-11e7-976a-719dea92027c.png)

**Comment by skade** [comment]
The "index.html" document is shared between all presentations and is just the "loader" document for all these, setting up the react framework and choosing the right chapter to load.

**Comment by skade** [comment]
Ah. Yeah, that's probably my attempt to make it work the way you had described once.

But I'd also be okay with different solutions, like linking to the TOC files from there. The current setup is a little confusing, I agree on that.

**Comment by emig** [comment]
Right, linking to TOC files LGTM. incoming PR
