### ISSUE TITLE
Dedicated Collections Chapter

### ISSUE THREAD

**Issue by Hoverbear** [skade/rust-three-days-course#8]
While writing the Standard Types chapter I'm thinking of covering

* Option
* Result
* Iterator
* Box

I also realized that the collections are very standard and common, but they are a topic all on their own.

**Comment by skade** [comment]
I would cover box and iterator in a chapter for each

**Comment by Hoverbear** [comment]
So Standard Types would be Option, Result (briefly, since it's in Error Handling as well), and Vec / Hashmap?

**Comment by skade** [comment]
Yep.

**Comment by Hoverbear** [comment]
I feel like much of the content that would be covered for collections was covered with the iterators and standard types chapter, closing.
